### ISSUE TITLE
question about the scan content feature

### ISSUE THREAD

**Issue by SpriteLin-ZJU** [gisbi-kim/SC-LIO-SAM#1]
Is Scan Content  descriptor only applicable to horizontally installed multi-ring lidars? If the lidar is installed obliquely, can this descriptor still be used?

**Comment by gisbi-kim** [comment]
Currently, we use the "z" value for the pixel value in a ScanContextDiscriptor, so it would show the best performance for the horizontally adjusted points (where the ground is perpendicular the z-axis)

but this not restrict the lidar's mounting angle. 
If you use IMU (i.e., knowing gravity direction) or known extrinsic parameter (i.e., mounting angle), 
you can rerotate a raw input point cloud to have a virtual coordinate having a z-axis perpendicular to the ground.

for example, in our original paper, https://irap.kaist.ac.kr/publications/gkim-2018-iros.pdf
we tested for the complex urban dataset, which has two obliquely mounted VLP16 lidar,
and we can say it works if we naively adjust the rotation with the known extrinsic parameter (perpendicular to the ground). 

I hope this could be an answer.

**Comment by SpriteLin-ZJU** [comment]
Thanks for your reply! I will read the paper for more detail.
