### ISSUE TITLE
Warning for deletion of contents in savePCDDirectory

### ISSUE THREAD

**Issue by nkhedekar** [gisbi-kim/SC-LIO-SAM#10]
It would be good (and perhaps necessary :sweat_smile: ) to put a warning comment here notifying users that the contents of the savePCDDirectory will be deleted with `rm -rf` and not simply overwritten. 
https://github.com/gisbi-kim/SC-LIO-SAM/blob/3660a877387171174a4a2c27123426604cf749a4/SC-LIO-SAM/config/params_liosam.yaml#L23

**Comment by gisbi-kim** [comment]
@nkhedekar I add the warning line!
https://github.com/gisbi-kim/SC-LIO-SAM/blob/d43ca00d97a756303c10975e32e8d66bfabb337d/SC-LIO-SAM/config/params_liosam.yaml#L23

Thanks for the suggestion!
