### ISSUE TITLE
Error on running launch file

### ISSUE THREAD

**Issue by ManChrys** [gisbi-kim/SC-LIO-SAM#11]
Hello

when im running the following command 

`roslaunch lio_sam run.launch`

i have the following error

![Screenshot from 2021-07-29 13-08-47](https://user-images.githubusercontent.com/67521662/127473835-67d49b86-e183-4f1f-8d91-e3794b3f0ab4.png)

As i notice i have this error in all LIO-SAM projects and the reasons are the imuPreinegration and mapOptimization.

I've installed sudo apt-get install libparmetis-dev so idk whats going on here.

Any help would be appreciated.

**Comment by gisbi-kim** [comment]
@ManChrys first could you check the imu and lidar topic flows and their timestamps? 
are they syncronized?

e.g., rostopic echo /imu > log.txt
then, you can open the log file and can find time

ps. you can rather use the lidar-only version. please see https://github.com/gisbi-kim/SC-A-LOAM

**Comment by ManChrys** [comment]
@gisbi-kim 

Hello my friend and thanks for the fast responses.  I found that the reason for the above error was the gtsam. I remove every gtsam file and i installed again 

wget -O ~/Downloads/gtsam.zip https://github.com/borglab/gtsam/archive/4.0.2.zip
cd ~/Downloads/ && unzip gtsam.zip -d ~/Downloads/
cd ~/Downloads/gtsam-4.0.2/
mkdir build && cd build
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
sudo make install -j8
