### ISSUE TITLE
Can i play SC-LIO-SAM using rosbag generated by kitti2bag?

### ISSUE THREAD

**Issue by Mineweeper** [gisbi-kim/SC-LIO-SAM#3]
Instead of MulRan dataset, can i use other kinds of dataset or rosbag recorded by myself? Thanks for your work.

**Comment by gisbi-kim** [comment]
Sure. you can change only the topic name in the yaml configuration file.
https://github.com/gisbi-kim/SC-LIO-SAM/blob/master/SC-LIO-SAM/config/params_mulran.yaml

for KITTI dataset, 
you can use this kind of simple read-and-publish without making rosbag file  
- https://github.com/gisbi-kim/mini-kitti-publisher

Thank you for using sc-lio-sam.

**Comment by Mineweeper** [comment]
Thanks for quick replying and awsome work!

**Comment by Mineweeper** [comment]
Would you please make some further introduction about mini-kitti-publisher? For example which timestamp.txt file in KITTI file should be the time.txt required by mini-kitti-publisher. And how should I change the topic name in yaml file in accordance with mini-kitti-publisher? Thanks again.

**Comment by gisbi-kim** [comment]
you first need to download the KITTI dataset here, http://www.cvlibs.net/datasets/kitti/eval_odometry.php
and the files will be found in there.

**Comment by Mineweeper** [comment]
Okay,I may download that later. Thanks again

**Comment by isqjsnao** [comment]
> Instead of MulRan dataset, can i use other kinds of dataset or rosbag recorded by myself? Thanks for your work.
Hello, why does the mapOptmization node start reporting errors when I run the mulran.launch file, while other launch files run without any issues
