### ISSUE TITLE
The global map disappear after a period of time

### ISSUE THREAD

**Issue by 14212094** [gisbi-kim/SC-LIO-SAM#4]
Hello Kim,i am a new learner of lidar slam.Thank you for  sharing your great job.Here is my problem:
I tried SC-LIO-SAM with the kaist01 dataset of mulran.The global map starts to disappear a period time,as the picture shown below:
![disappear](https://user-images.githubusercontent.com/38451498/110272813-08c1a680-8006-11eb-9455-9d69fd4fd2a4.png)
the red box of the picture.
I didnt encounter this problem when i tried kaist01 with the SC-LEGOLOAM.
I guess there are some parameters about the visualization time which can be modified，but i cannot find it.
Thank you!

**Comment by gisbi-kim** [comment]
Hi @14212094, thank you for using our system. 

I also noticed the issue too, and I'm under finding the reason.

but I NOTE that the disappearing submap is only about the visualization issue, 
and not having any bad effect on the motion estimation

so after running the program, you can find the result like https://github.com/gisbi-kim/SC-LIO-SAM#applications
and you would check all the estimation is alright.

if you need the optimized stacked map, 
I recommend you 
to use the saved Scans and the optimized poses using https://github.com/gisbi-kim/SC-LIO-SAM#applications
for the details of making  a map by integrating (stacking) scans using the poses, 
see here https://drive.google.com/drive/folders/1zYVHzpPPhTEEb-Kb-N1Kg_7nhB_44XSo
(tutorial video https://www.youtube.com/watch?v=rYIAXSQshtk)

**Comment by 14212094** [comment]
@gisbi-kim OK!Thank you for sharing the video and the matlab code for making submap.
