### ISSUE TITLE
[lio_sam_mapOptmization-4] process has died

### ISSUE THREAD

**Issue by IaroslavS** [gisbi-kim/SC-LIO-SAM#5]
```

**Comment by llxClover** [comment]
My LIO-SAM can run, but the SC-LIO-SAM can't run.
Could you tell me what I should @IaroslavS

**Comment by IaroslavS** [comment]
> My LIO-SAM can run, but the SC-LIO-SAM can't run.
> Could you tell me what I should @IaroslavS

Hi, could you provide the error message ?

**Comment by llxClover** [comment]
> > My LIO-SAM can run, but the SC-LIO-SAM can't run.
> > Could you tell me what I should @IaroslavS
> 
> Hi, could you provide the error message ?

Thank you for your reply timely！I have solved the problem by removing gtsam4.0.2 and installing gtsam4.0.2 again. But I don't know what the problem is.

**Comment by L00qqq** [comment]
My Display ：  malloc(): memory corruption
[lio_sam_mapOptmization-4] process has died [pid 14922, exit code -6, cmd

![Uploading screenshot-20240102-162616.png…]()

**Comment by L00qqq** [comment]
My Display ： malloc(): memory corruption
[lio_sam_mapOptmization-4] process has died [pid 14922, exit code -6, cmd


![screenshot-20240102-162616](https://github.com/gisbi-kim/SC-LIO-SAM/assets/152479185/55fc9c95-fd76-4a51-a292-2ddf645e40c6)

**Comment by IaroslavS** [comment]
> malloc(): memory corruption

Please, open new issue with new issue name like "malloc(): memory corruption" or something like that.
