### ISSUE TITLE
I still lack some files after following your video tutorial.How do I use this to get data for the removert？

### ISSUE THREAD

**Issue by 13159851972** [gisbi-kim/SC-LIO-SAM#6]
First of all, thank you very much for your open source algorithm, which benefits me a lot， but there are still some things I don't understand.
I followed this video tutorial：https://www.youtube.com/watch?v=UiYYrPMcIRU
But I only got five ".pcd " such as " cloudCorner.pcd" "cloudGlobal.pcd" "cloudSurf.pcd" "trajectory.pcd" "transformations.pcd" ,I can't find a txt name "optimized_poses.txt" and I don't have a document save so many ".pcd" like "000xxx.pcd" 
Is there something I'm missing?

**Comment by gisbi-kim** [comment]
hmm weird. Did you check this line? 
https://github.com/gisbi-kim/SC-LIO-SAM/blob/ff6ea6b6c1ea0319f941065980fe11a1b240048d/SC-LIO-SAM/config/params_mulran.yaml#L16

**Comment by 13159851972** [comment]
Thank you for your reply. I have modified my parameter file according to the tutorial, but I still can't get as much as 'xxx.pcd' and 'xxx.scd'   in your video.I only get five pcd name: " cloudCorner.pcd" "cloudGlobal.pcd" "cloudSurf.pcd" "trajectory.pcd" .I can't find a folder name ' Scans ' or 'SCDs' in my set folder.
I would like to ask is it possible to run the program according to the input instructions of the video tutorial and get many '.pcd' and '.scd'  directly? Or do I need some extra steps?

**Comment by gisbi-kim** [comment]
@13159851972  ok. I'm gonna do myself again and will report it within a few days.

**Comment by 13159851972** [comment]
![图片](https://user-images.githubusercontent.com/56250663/114878705-194e1380-9e33-11eb-91a9-2c448f694a8b.png)
This is the file I got when I ran the program

**Comment by 13159851972** [comment]
![图片](https://user-images.githubusercontent.com/56250663/114879609-f112e480-9e33-11eb-8e99-c55d0cd3333e.png)
This is the file i see in your video.
I'm sorry that the question is a waste of your time.Thank you very much for your open source algorithm and help anyway.
I would like to ask if it is convenient for you to directly send me a data that can be directly used in the program 'removert'? 
I'm more interested in trying out your open source algorithm 'removert'

**Comment by gisbi-kim** [comment]
@13159851972 sorry for the late response, 

then, could you try the saver from the non-imu version of this repo? 
see https://github.com/gisbi-kim/SC-A-LOAM
