### ISSUE TITLE
Permissions denied.

### ISSUE THREAD

**Issue by Mikor-mkr** [gisbi-kim/SC-LIO-SAM#8]
Hi everyone,
after launching the run.launch file I get this as part of my output and I do not know how to deal with it, any ideas?

```
rm: cannot remove '/home/user/Desktop/data/scliosam/': No such file or directory
mkdir: cannot create directory ‘/home/user/Desktop/data/scliosam/’: No such file or directory
rm: cannot remove '/home/user/Desktop/data/scliosam/SCDs/': No such file or directory
mkdir: cannot create directory ‘/home/user’: Permission denied
rm: cannot remove '/home/user/Desktop/data/scliosam/Scans/': No such file or directory
mkdir: cannot create directory ‘/home/user’: Permission denied
```

**Comment by minwoo0611** [comment]
Hello. @Mikor-mkr 
I think that you have to write your user name in your save path.
For example, you should use save path /home/Mikor-mkr/Desktop/data/scliosam, not using user.
I hope this will solve your problem.

**Comment by gisbi-kim** [comment]
@Mikor-mkr 

The answer from @minwoo0611 is right, as he said, please adjust the path for your system.
